/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Controller_MainPage */

#ifndef _Included_application_Controller_MainPage
#define _Included_application_Controller_MainPage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_Controller_MainPage
 * Method:    getSchedule
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_application_Controller_1MainPage_getSchedule
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
